spring:
  application:
    name: user-service
springdoc:
  swagger-ui:
    url: /user-service.yaml
    path: /swagger-ui.html
secret:
  key: mySuperSecretKey
  access-duration: 3600
  refresh-duration: 86400
  issuer: user-service